//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GespharmWeb.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentCommander
    {
        public int IdMedicamentCommander { get; set; }
        public int IdMedicament { get; set; }
        public int IdCommande { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Medicament Medicament { get; set; }
    }
}
